### ISSUE TITLE
Run entire test suite against built Phar

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3950] opened 2017-03-30 11:59 UTC
In splitting commands to external packages (#3728), one feature we've lost is having the entire test suite run against the built Phar. Because of this, bugs like https://github.com/wp-cli/server-command/issues/13 can occur.

We should continue to run the entire test suite against the built Phar. There are a couple of ways we could do this:

1. Use Travis' beta cron feature to schedule a nightly job.
2. Abstract Phar building to a separate repository, and have it run the entire test suite before it pushes the Phar build to the builds repo.

**Comment by schlessera** [comment] 2017-05-09 16:17
From Slack:

The general approach I would like to take is to have a separate repository be responsible for building the Phar (to get these build tools out of the main framework repo, and more importantly, to get a separate `composer.son` for the Phar). The Travis CI tests for this repo would then test the framework together with all bundled commands.

If the `wp-cli/wp-cli` in the `composer.json` of this repo is versioned against a specific commit, we could generate a pull request whenever there's a push to `wp-cli/wp-cli:master`. This pull request would contain a commit to adapt the `wp-cli/wp-cli` version in `composer.json`, and thus cause the Travis CI to run the tests for the entire Phar suite against that commit.

The pull requests could be automatically merged as long as the tests ran successfully. If not, we'll get a notification.

**Comment by danielbachhuber** [comment] 2017-05-09 17:16
> If the `wp-cli/wp-cli` in the `composer.json` of this repo is versioned against a specific commit, we could generate a pull request whenever there's a push to `wp-cli/wp-cli:master`

Interesting idea.

How would you handle, say, three pull requests merged in a close time frame, which would generate three separate (conflicting) branches?

**Comment by schlessera** [comment] 2017-05-09 17:30
Maybe just run a nightly with the latest commit? Would that be sufficient?

**Comment by danielbachhuber** [comment] 2017-05-09 17:34
> Maybe just run a nightly with the latest commit? Would that be sufficient?

I'd like to be more frequent than this.

We could also commit and push to master. Although, then we run into the other problem of jobs being tied up.

**Comment by schlessera** [comment] 2017-05-18 16:27
So, I'm currently playing around with this.

I have a script that runs the tests across all commands after a `composer install` of the latest `wp-cli/wp-cli:dev-master`. We might add a different one specific for the Phar nightly as well, but I think the "on-going development" is more important right now. Chances that the Phar nightly breaks although the `composer install` succeeds are pretty slim.

The question ow is what to do when these tests fail.

In the beginning I thought about creating pull requests to let the tests run through Travis, but then we'll have a lot of trouble getting rid of these pull requests. So now, the tests are run through the cron job (which I hope is no problem for the server you wanted to run these on). This allows us to act on the failures in a more differentiated way.

What I want to do is to let the tests for each command run, catch the output, and if that test failed, create an issue in the repo of that command with the test output as ticket.

However, I don't want to flood the commands with issues if we don't get to immediately fix something. My current thinking therefore is to make sure we only ever have one issue about the tests currently failing. The issue should contain the hashes of the `wp-cli/wp-cli` and the command refs it was run against. For a failed test:
- If an issue with the same refs already exists, move on.
- If an issue with the same refs does not yet exist, close all issues with other refs and create a new one with the current refs.

**Comment by danielbachhuber** [comment] 2017-05-18 16:34
Creating new issues seems like overkill. Let's go with the easiest possible implementation, which would be either:

1. Reporting the test failure to Slack, a la WordPress
2. Using Travis' email feature to send a build failure email to an address

> Chances that the Phar nightly breaks although the `composer install` succeeds are pretty slim.

Slim, but catastrophic. One common failure for the Phar nightly is that files are missing from the build.

I think we need to build the Phar (or reuse the one that's already built), and run the tests against the built Phar. Historically, the test suite has always run against the built Phar.

**Comment by schlessera** [comment] 2017-05-18 16:53
> Reporting the test failure to Slack, a la WordPress
I'll send to Slack `#cli-firehose`.

> Slim, but catastrophic. One common failure for the Phar nightly is that files are missing from the build.
Okay, that would indeed be bad. But I think I can just add the Phar building and then set the `wp` executable to use for Behat...

**Comment by schlessera** [comment] 2017-05-18 16:55
Command repos are now extracted out of the `composer.json` file:
```
REPOS=$(cat composer.json | grep -oE "wp-cli/([a-z\-]*)-command")
```
Very naïve approach, but good enough I'd say.

**Comment by schlessera** [comment] 2017-05-30 17:20
Test suite seems to run as intended.

Hooking it up to the release process will be tackled in https://github.com/wp-cli/wp-cli/issues/4108

**Closed by schlessera** 2017-05-30 17:20 UTC
Labels: scope:testing
