### ISSUE TITLE
Composer deprecation notices: Class ... does not comply with psr-0 autoloading standard.

### ISSUE THREAD

**Issue by mikeschinkel** [wp-cli/wp-cli#5365] opened 2020-03-14 14:31 UTC
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

When the following is in the `composer.json` file of a WordPress project that is using Composer to manage dependencies:

```
"require-dev": {
	"wp-cli/wp-cli-bundle": "^2.4"
},
```
Running `composer install` with Composer version `1.10.1` generates four (4) deprecation notices saying:

```
Deprecation Notice: Class XXX ... does not comply with psr-0 autoloading standard. 
It will not autoload anymore in Composer v2.0.
```

This is problematic as we need to fail during CI/CD if Composer generates a deprecation notice because the error might be our code.

**Describe how other contributors can replicate this bug**

- Ensure you have Composer `v1.10` or later installed.
- Run `composer require-dev wp-cli/wp-cli-bundle` on a project.
- Run `composer install`.
- See the deprecation notices in the attached screenshot.

**Describe what you expect as the correct outcome**

That Composer would not generate deprecation notices for WP-CLI.

**Let us know what environment you are running this on**

```
OS:	Darwin 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64
Shell:	/bin/bash
PHP binary:	/usr/local/Cellar/php/7.3.6/bin/php
PHP version:	7.3.6
php.ini used:	/usr/local/etc/php/7.3/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/mikeschinkel/Sites/wp-cl2.local/www/wp-content/mu-plugins/client-name/common
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.2.0
```

**Provide a possible solution**

Rework the class hierarchy so that it is compatible with `PSR-0`.  I would be happy to submit a patch but I assume that restructuring the directory hierarchy is something you'd want to do yourself.

**Provide additional context/screenshots**

![composer-deprecation-notices](https://user-images.githubusercontent.com/153285/76683992-ac889a00-65de-11ea-994c-ce4c5f9a8417.png)

**Comment by jenkoian** [comment] 2020-03-20 11:10
This is a duplicate of https://github.com/wp-cli/wp-cli/issues/5364 but this one is written up better (and includes pictures!) so will close mine 😃

**Comment by leopoiroux** [comment] 2020-03-24 22:25
+1

**Comment by jenkoian** [comment] 2020-05-19 09:41
Composer 2 tentatively set for June https://blog.packagist.com/composer-2-development-update/ so would be good to try and get this addressed before then if at all possible 🤞

**Comment by jenkoian** [comment] 2020-06-03 12:03
Now in alpha, please consider looking into this asap https://github.com/composer/composer/releases/tag/2.0.0-alpha1

**Closed** 2020-06-04 17:49 UTC

**Comment by redtux** [comment] 2020-09-27 20:32
Hi everybody! Has this been fixed?

FYI: I am still getting the same warning (on latest Ubuntu 20.04.1 LTS).

```sh
composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating optimized autoload files
Deprecation Notice: Class WP_CLI located in ./vendor/wp-cli/wp-cli/php/class-wp-cli.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201                             
Deprecation Notice: Class WP_CLI_Command located in ./vendor/wp-cli/wp-cli/php/class-wp-cli-command.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201             
```

```sh
composer --version
Composer 1.10.1 2020-03-13 20:34:27
```

```sh
./vendor/wp-cli/wp-cli/bin/wp --info
OS:     Linux 5.4.0-49-generic #53-Ubuntu SMP Fri Sep 18 09:54:57 UTC 2020 x86_64
Shell:  /bin/zsh
PHP binary:     /usr/bin/php
PHP version:    7.4.3
php.ini used:   /etc/php/7.4/cli/php.ini
WP-CLI root dir:        /home/redtux/Projects/wp/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      /home/redtux/Projects/wp/vendor
WP_CLI phar path:
WP-CLI packages dir:
WP-CLI global config:   
WP-CLI project config:  /home/redtux/Projects/bookstore/panda/wp-cli.yml
WP-CLI version: 2.4.0
```

**Comment by jenkoian** [comment] 2020-09-28 08:35
@redtux not released yet, coming in [2.5.0](https://github.com/wp-cli/wp-cli/milestone/64) I believe

**Comment by rubas** [comment] 2020-10-30 11:02
Composer 2.0 is out since 6days ...

https://github.com/composer/composer/releases/tag/2.0.0

**Comment by leopoiroux** [comment] 2021-05-03 07:21
> @redtux not released yet, coming in [2.5.0](https://github.com/wp-cli/wp-cli/milestone/64) I believe

Hi @jenkoian, when will the 2.5 version be available?

**Comment by jenkoian** [comment] 2021-05-04 09:15
@leopoiroux I don't work on the project so couldn't tell you, but I guess when this is 100% https://github.com/wp-cli/wp-cli/milestone/64

**Comment by jenkoian** [comment] 2021-05-13 10:19
Good news @leopoiroux - https://make.wordpress.org/cli/2021/05/13/wp-cli-v2-5-0-release-date/
