### ISSUE TITLE
Update themes/plugins from GitHub zip

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#3675] opened 2016-12-19 13:06 UTC
`wp plugin install https://github.com/envato/wp-envato-market/archive/master.zip` works quite well, strips off `-master` from the folder name.

Could we have zip-based plugin updates?

**Comment by szepeviktor** [comment] 2016-12-19 13:10
Untill then

```bash
#!/bin/bash

WP_CONTENT_DIR="$(wp eval 'echo WP_CONTENT_DIR;')"

if [ -n "$WP_CONTENT_DIR" ] && [ -d "$WP_CONTENT_DIR" ]; then
    rm -rf "${WP_CONTENT_DIR}/plugins/wp-envato-market"
    wp plugin install "https://github.com/envato/wp-envato-market/archive/master.zip"
fi
```

**Comment by danielbachhuber** [comment] 2016-12-20 14:11
Duplicate of #2394

 You can run `wp plugin install --force <plugin|zip|url>` to achieve the same effect.

**Closed by danielbachhuber** 2016-12-20 14:11 UTC

**Comment by szepeviktor** [comment] 2016-12-20 17:29
Thank you.
