### ISSUE TITLE
Custom wp-config.php

### ISSUE THREAD

**Issue by AlexeyKrivoruchko** [wp-cli/wp-cli#2402] opened 2016-01-21 22:34 UTC
Dear community,

Thank you so much for building WP-CLI. It’s a great work, and I find it very useful to have a command line interface for WordPress. I’ve ran across a little issue with it in one of the project setups I happen to work with.

I load custom configuration files based on an environment variable to support various environments, so I have a special edition of wp-config.php for each of them.

WP-CLI is not loading custom files, and therefore looks for database connection parameters in the primary wp-config.php, which is nothing but a loader of a proper wp-config-env file in my case, so it gives me an error like this:
<br>
Error: 
<h5>Error establishing a database connection</h5>
<p>This either means that the username and password information in your <code>wp-config.php</code> file is incorrect or we can't contact the database server at <code>localhost</code>. This could mean your host's database server is down.</p>
<ul>
    <li>Are you sure you have the correct username and password?</li>
    <li>Are you sure that you have typed the correct hostname?</li>
    <li>Are you sure that the database server is running?</li>
</ul>
<p>If you're unsure what these terms mean you should probably contact your host. If you still need help you can always visit the <a href='https://wordpress.org/support/'>WordPress Support Forums</a>.</p>
<br>

As I understand, I am not the only person who needs to load custom config files, so I wanted to come up with a suggestion. One of the ways to work this around would be to add a --config-path option to let WP-CLI know where the actual config is.

There might be other ways, so please feel free to comment and let me know! If not, I’d try to come up with a pull request with this option if this is of interest, maybe someone will find it helpful in the future. 

Thanks

**Comment by danielbachhuber** [comment] 2016-01-21 23:41
Can you share your `wp-config.php` file, with any secrets removed?

**Comment by rmccue** [comment] 2016-01-22 04:39
Duplicate of #1631, I think? Related: #1362, #1667

**Comment by AlexeyKrivoruchko** [comment] 2016-01-22 10:47
My <code>wp-config.php</code> file.

<?php

// Disables all auto updates.
define( 'AUTOMATIC_UPDATER_DISABLED', true );
// Disables all core updates.
define( 'WP_AUTO_UPDATE_CORE', false );
// Disable editing theme files via wp-admin
define( 'DISALLOW_FILE_EDIT', true );
// Disable native WP-cron
define( 'DISABLE_WP_CRON', true );
// Set localization language
define( 'WPLANG', 'ru_RU' );

if ( isset( $_SERVER['MY_ENV'] ) && $_SERVER['MY_ENV'] ) {
	$env = $_SERVER['MY_ENV'];
}
define( 'MY_ENV', $env );

// <code>wp-config-example.php</code>, where my DB connection
$configFile = __DIR__ . '/wp-config-' . MY_ENV . '.php'; 

include_once( $configFile );

/** Absolute path to the WordPress directory. */
if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');

/** Sets up WordPress vars and included files. */
require_once(ABSPATH . 'wp-settings.php');

**Comment by danielbachhuber** [comment] 2016-01-22 17:32
@AlexeyKrivoruchko You'll need to either set the environment variable you're expecting when running WP-CLI, or change your conditional to use a default config file when WP-CLI is present.

```
$ MY_ENV=dev wp option get home
```

or

```
if ( isset( $_SERVER['MY_ENV'] ) && $_SERVER['MY_ENV'] ) {
    $env = $_SERVER['MY_ENV'];
} else if ( defined( 'WP_CLI' ) && WP_CLI ) {
    $env = 'dev';
}
```

Related #2365

**Closed by danielbachhuber** 2016-01-22 17:32 UTC
Labels: state:unconfirmed

**Comment by danyalette** [comment] 2016-01-22 22:41
because of how common this issue appears to be, it might make sense for wp-cli itself to set an environment variable? i can imagine a variety of situations, beyond loading the config, that could benefit from the ability to detect whether the request is coming from wp-cli

**Comment by danielbachhuber** [comment] 2016-01-22 22:45
> because of how common this issue appears to be

It's not a common issue.

>  it might make sense for wp-cli itself to set an environment variable?

I don't see how this would solve the problem? How would WP-CLI know which environment variable to set for you?

> i can imagine a variety of situations, beyond loading the config, that could benefit from the ability to detect whether the request is coming from wp-cli

You can use:

```
if ( defined( 'WP_CLI' ) && WP_CLI )
```

`WP_CLI` is a constant that only WP-CLI defines. Or should, at least.

**Comment by danyalette** [comment] 2016-01-22 23:16
@AlexeyKrivoruchko: as per @danielbachhuber you can bypass the need for an env var and simply check for 
```
if ( defined( 'WP_CLI' ) && WP_CLI ) 
```
in your config.php

Everyone on Pantheon attempting to use wp-cli will encounter this issue. 
Pantheon advocates the use of wp-cli.

**Comment by AlexeyKrivoruchko** [comment] 2016-01-22 23:57
Thank you, that worked. I use env setting option!

**Comment by agentmoller001** [comment] 2016-08-10 19:18
Thanks! I was receiving the same error as well.
**Error establishing a database connection**

`if ( defined( 'WP_CLI' ) && WP_CLI )` worked great.

I needed to use a TCP connection for wp-cli instead of a Unix socket. Adding this to the wp-config.php fixed my issue as well.
```
/** Tell WP-CLI to use TCP instead of socket connection */
if ( defined( 'WP_CLI' ) && WP_CLI ) {

/** MySQL hostname for WP-CLI */
define('DB_HOST', '127.0.0.1:3306');

} else {

/** MySQL hostname */
define('DB_HOST', 'localhost:3306'); }
```
Reference - https://www.howtoforge.com/community/threads/ispconfig-3-wp-cli.73682/#post-346741
