### ISSUE TITLE
WP test suite prior to 4.0 is buggy

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#2155] opened 2015-10-15 19:48 UTC
Follow-up to #2050.

Looks like the WP test suite prior to 4.0 was buggy, for example `did_action( $action )` appears to always return `0`. This means if your plugin is testing the return value of `did_action()`, it'll get an unexpected failure.

I wonder if it's an idea to use the current tag for the test suite, but only back to 4.0, and use 4.0 if a version lower than that is being tested?

**Comment by danielbachhuber** [comment] 2015-10-15 21:21
Ugh.

> I wonder if it's an idea to use the current tag for the test suite, but only back to 4.0, and use 4.0 if a version lower than that is being tested?

I don't really want to maintain one-off logic if I don't have to. This may not be the only incompatibility.

> This means if your plugin is testing the return value of did_action(), it'll get an unexpected failure.

Is this test failure somewhere I can see? It'd be nice to track down the root cause.

**Comment by johnbillion** [comment] 2015-10-15 21:33
> Is this test failure somewhere I can see? It'd be nice to track down the root cause.

https://travis-ci.org/johnbillion/user-switching/builds/85599880

**Comment by johnbillion** [comment] 2015-10-15 21:35
Looks like the problem is actually that `did_action()` doesn't get reset. In the job above the test fails because it's expecting 0 but getting 2.

**Comment by keesiemeijer** [comment] 2015-10-16 22:33
Same with filters. If you use a filter in one test, and then in another, the filtered value from the first test is used in the filter for the second test. Remove the filters and actions you use in your tests in a [tearDown()](https://phpunit.de/manual/current/en/fixtures.html) (for versions < 4.0).

**Comment by keesiemeijer** [comment] 2015-10-16 23:21
I think WP-CLI test scaffolding should always use the test suite from the same branch as the WP version used in the tests. The test scaffolding should be a boilerplate and should not introduce unnecessary complications by adding a conditional for the version of the test framework used. Developers can change the created files to load whatever version they want or rewrite their tests to comply with older versions.

**Comment by danielbachhuber** [comment] 2015-10-25 19:37
@johnbillion are you alright punting on this, or is there a solution you'd like to move forward with?

**Comment by johnbillion** [comment] 2015-10-27 08:28
Personally I'd like to set the minimum test suite version to 4.0 even if <4.0 is being tested, but I'm not overly fussed about it. I've altered the test install script for my plugins where this is a problem.

**Comment by danielbachhuber** [comment] 2015-10-29 13:54
I think we'll call this wontfix for now, and we can come back to it later if it turns out to be a huge problem.

**Closed by danielbachhuber** 2015-10-29 13:54 UTC
Labels: bug, scope:command
