### ISSUE TITLE
WP-CLI 1.2 does not recognize custom commands whose names contain spaces

### ISSUE THREAD

**Issue by philipnewcomer** [wp-cli/wp-cli#4122] opened 2017-06-02 10:35 UTC
We have some custom commands whose names contain spaces. That has always worked fine until the 1.2 release of WP-CLI, after which they are no longer recognized.

To reproduce, place the following file in an mu-plugin: https://gist.github.com/philipnewcomer/73b2405aae3ffed4ee3fe2e51fada4b7

Before WP-CLI 1.2:
```
$ wp foo bar
Success: Hello world!
```

After updating to 1.2:
```
$ wp foo bar
Error: 'foo' is not a registered wp command. See 'wp help'.
```

If I simply change the name of the command to `foobar` instead of `foo bar` and run `wp foobar`, it works as expected on 1.2.

**Comment by AaronHolbrook** [comment] 2017-06-02 10:40
+1; I have used this numerous times to create sub commands, and not having this ability will break existing usages quite heavily.

**Comment by schlessera** [comment] 2017-06-02 10:44
Using spaces in commands should still work, as WP-CLI uses this itself, for example for the `network meta` command, where no `network` parent exists: https://github.com/wp-cli/entity-command/blob/master/entity-command.php#L17

I'll test this on my local machine to see what the problem might be...

**Comment by schlessera** [comment] 2017-06-02 10:48
@philipnewcomer A first test with your gist through a require command cannot reproduce this:

![screenshot 2017-06-02 12 47 13](https://cloud.githubusercontent.com/assets/83631/26722741/a042d4f4-4791-11e7-814d-0ad202395ad7.png)

For now I have to assume this might have something to do with your specific platform. Can you share more details that could help replicate the issue?

**Comment by philipnewcomer** [comment] 2017-06-02 10:58
@schlessera it works for me as well when I use the require command like you did. However, it's broken when the command is included as an mu-plugin, with wp-cli-test.php placed in the mu-plugins directory and not loaded through the require command.

**Comment by schlessera** [comment] 2017-06-02 11:04
@philipnewcomer I can confirm now that this breaks for plugins and mu-plugins. Our tests did not cover this specific scenario.

I'll investigate and update you as soon as we have a fix.

**Comment by schlessera** [comment] 2017-06-02 11:36
@philipnewcomer I have fixed the issue in https://github.com/wp-cli/wp-cli/pull/4123

As soon as this is merged and the next nightly is built, you can update to the latest nightly with `wp cli update --nightly` to get the fix.

**Comment by danielbachhuber** [comment] 2017-06-02 12:07
We'll need to release a 1.2.1 for this.

**Comment by danielbachhuber** [comment] 2017-06-03 12:38
@schlessera We actually need to run this after the `after_wp_load` hook, because commands can be registered on the `after_wp_load` hook

Generally, a better approach may be to process these deferred commands immediately before WP-CLI tries to resolve and run them

**Closed** 2017-06-05 17:19 UTC
Labels: bug, internal-api:wp-cli-add-command, scope:bootstrap, scope:framework
