### ISSUE TITLE
PHP Notice on $ wp plugin install

### ISSUE THREAD

**Issue by obstschale** [wp-cli/wp-cli#2752] opened 2016-05-15 15:46 UTC
Hey there,

I just installed [WP Starter](https://github.com/wecodemore/wpstarter) in my VM and was curious if WP-CLI is working with it. I ssh-ed into the VM and dir into `/path/to/project/wp` and is seems everything works just fine.

So I thought. If I run `wp plugin install <slug>` I get a PHP Notice. The command actually works and the plugin is installed. But I thought I post this here for your notice.

```sh
$ wp plugin install backwpup
PHP Notice:  Undefined offset: 4 in phar:///usr/local/bin/wp/php/WP_CLI/DocParser.php on line 124
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/wp:0
PHP   2. include() /usr/local/bin/wp:4
PHP   3. include() phar:///usr/local/bin/wp/php/boot-phar.php:5
PHP   4. WP_CLI\Runner->start() phar:///usr/local/bin/wp/php/wp-cli.php:21
PHP   5. WP_CLI\Runner->_run_command() phar:///usr/local/bin/wp/php/WP_CLI/Runner.php:757
PHP   6. WP_CLI\Runner->run_command() phar:///usr/local/bin/wp/php/WP_CLI/Runner.php:334
PHP   7. WP_CLI\Dispatcher\Subcommand->invoke() phar:///usr/local/bin/wp/php/WP_CLI/Runner.php:327
PHP   8. WP_CLI\Dispatcher\Subcommand->validate_args() phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:342
PHP   9. WP_CLI\DocParser->get_arg_args() phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:261
# Below: Normal WP-CLI output for installing plugins in german
Installing BackWPup – WordPress Backup Plugin (3.3.1)
Runterladen des Installationspakets von https://downloads.wordpress.org/plugin/backwpup.3.3.1.zip...
Entpacken des Pakets...
Das Plugin wird installiert...
Das Plugin wurde erfolgreich installiert.
```

***

```sh
$ wp --version
WP-CLI 0.23.1

$ php --version
PHP 7.0.5-2+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
    with blackfire v1.10.4, https://blackfire.io, by Blackfireio Inc.
```

**Comment by danielbachhuber** [comment] 2016-05-15 17:38
Duplicate of #2627

**Closed by danielbachhuber** 2016-05-15 17:38 UTC
