### ISSUE TITLE
Update user password exception

### ISSUE THREAD

**Issue by Santana1053** [wp-cli/wp-cli#3374] opened 2016-09-02 20:13 UTC
I can update any part of a user except the password. when I try to update the user_pass i get the following error
```
PHP Fatal error:  Uncaught exception 'phpmailerException' with message 'Invalid address: wordpress@' in /wp-includes/class-phpmailer.php:946
Stack trace:
#0 /wp-includes/pluggable.php(352): PHPMailer->setFrom('wordpress@', 'WordPress')
#1 /wp-includes/user.php(1841): wp_mail('contact@maudien...', '[Ackerman Plumb...', 'Hi maudience,??...', '')
#2 phar:///usr/local/bin/wp/php/WP_CLI/CommandWithDBObject.php(73): wp_update_user(Array)
#3 phar:///usr/local/bin/wp/php/commands/user.php(403): WP_CLI\CommandWithDBObject->_update(Array, Array, 'wp_update_user')
#4 [internal function]: User_Command->update(Array, Array)
#5 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(67): call_user_func(Array, Array, Array)
#6 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#7 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(372): call in /wp-includes/class-phpmailer.php on line 946
```

**Comment by danielbachhuber** [comment] 2016-09-02 20:25
Hi @Santana1053,

Github issues are no longer an appropriate venue for support questions. Please review http://wp-cli.org/#support

**Comment by Ipstenu** [comment] 2016-09-19 18:10
FYI this is the bug in core - https://core.trac.wordpress.org/ticket/37736

**Comment by Ipstenu** [comment] 2016-09-19 18:32
@danielbachhuber - I see 'why' it's failing, but I have no idea why it's failing NOW and not a million years ago.

https://core.trac.wordpress.org/browser/trunk/src/wp-includes/pluggable.php#L324

That has this:

`$sitename = strtolower( $_SERVER['SERVER_NAME'] );`

That's a problem because it _will not_ work on command line. Why? When you run PHP via CLI, it doesn't know about your webserver, so there's no Server name :(

I don't know why this was working before, though. That seems weird, since THAT part of the code hasn't changed in a long time.

@rmccue opined this:

> Wonder if it was changed as a side-effect of the wp-cli loading changes with wp-settings

Which is very possible. It's not setting the server name so it's going to fail :(

**Comment by danielbachhuber** [comment] 2016-09-19 21:00
> I see 'why' it's failing, but I have no idea why it's failing NOW and not a million years ago.

Yeah, I'm not sure why either at a glance.

**Comment by Ipstenu** [comment] 2016-09-19 23:13
I think Ryan's suggestion about the WP-settings change is the culprit. I'm unclear on how WP-cli used to pick up or pass through the domain name, but at a guess here if you defaulted --URL to the value of the main domain (i.e. Site URL) wouldn't that cover this and pretty much anywhere else that WP thinks it needs a domain? It would also stop plugins like Postfix SMTP and others that call server name from failing.

**Comment by danielbachhuber** [comment] 2016-09-20 14:37
> I think Ryan's suggestion about the WP-settings change is the culprit.

The wp-settings changes didn't have anything to do with setting of `$_SERVER['SERVER_NAME']`

> I'm unclear on how WP-cli used to pick up or pass through the domain name, but at a guess here if you defaulted --URL to the value of the main domain (i.e. Site URL) wouldn't that cover this and pretty much anywhere else that WP thinks it needs a domain?

The fix for this bug should be in WordPress core, I think.

**Comment by Ipstenu** [comment] 2016-09-20 15:55
I disagree (in part).

Yes it's a core bug, but in light of having the same flippin' argument on core (which I suspect will be "It's command line, we don't support that, don't care" or a remark of "Well if you can't debug it..." to me), would it not be best to have the discussion _here_ so the full situation and possible direction of a fix be passed on, rather than just passing the buck?

Because it _really_ sounds like you passing the buck (perhaps to me, perhaps to core) and sounding like you don't care. Which I know isn't true, but that's what happens when you say "No support here." without doing the modicum of troubleshooting to actually determine where the issue is, so we (the community) can actually get the bloody issue fixed. Because as it stands? Core works fine and wp-cli is broken, no matter who is at ultimate fault here.

So. Knowing sod-all about this, I did some basic troubleshooting testing to figure out more of what's going on, in the hopes that a core patch can be applied.

* WP 4.5.x - WP-CLI 0.24.1 - Works
* WP 4.6.x - WP-CLI 0.24.1 - Fails

This lends credence to your claim of 'It's a core bug.'

The changes made here - https://core.trac.wordpress.org/changeset/38058#file0 - had to do with changing $phpmailer from using FromName and From to setFrom:

`
        $phpmailer->FromName = apply_filters( 'wp_mail_from_name', $from_name );
        $phpmailer->From = apply_filters( 'wp_mail_from', $from_email );
`

Those were removed. So I added them back in and commented out this: `$phpmailer->setFrom( $from_email, $from_name );`

It works. Why? Well ... get this. `setFrom` actually _checks_ that the email is valid!!

This lends credence to _my_ theory of "Actually it's a wp-cli being cli bug."

I think this has actually _always_ been a bug in wp-cli, due to command line being command line, and we just never noticed because it was a silent fail.

**Comment by Clorith** [comment] 2016-09-20 16:16
I was hunting the email sending bug 37736, so I'd love to provide my input here.

I feel this is something that should be fixed on WP-CLI's side of things, core has been doing it wrong up until this point in time when we finally used phpmailer internals properly, and are now getting exceptions thrown when they should be in this case.

Ideally a sane default value for `$_SERVER['SERVER_NAME']` from siteurl should probably be applied by WP-CLI to address this (and potential other pitfalls we've just not realized exist from the lack of a super global).

**Comment by danielbachhuber** [comment] 2016-09-20 23:04
> Because it *really* sounds like you passing the buck (perhaps to me, perhaps to core) and sounding like you don't care. Which I know isn't true, but that's what happens when you say "No support here." without doing the modicum of troubleshooting to actually determine where the issue is, so we (the community) can actually get the bloody issue fixed.

Just to clarify, I'm drawing a line between what I'll take responsibility for fixing, and what I consider outside the scope of my responsibility to fix. I don't claim responsibility for troubleshooting every reported bug. Furthermore, how I spend my volunteered time isn't something I'm open to debating.

> Ideally a sane default value for `$_SERVER['SERVER_NAME']` from siteurl should probably be applied by WP-CLI to address this (and potential other pitfalls we've just not realized exist from the lack of a super global).

I don't think this is an easy change, and has the potential for unintended consequences.

At this point, I think the issue should be addressed with https://core.trac.wordpress.org/ticket/25239

**Comment by Ipstenu** [comment] 2016-09-20 23:22
I'll leave a comment in core trac. I am curious as to what unintended consequences? The only one that popped up is Multisite and activating plugins and themes, though I don't believe that would change wether or not you define the URL (i.e. it always default to mommy/main blog). But that's a different horse to chase down and well OT.

**Comment by danielbachhuber** [comment] 2016-09-20 23:31
> I am curious as to what unintended consequences?

Things breaking unexpectedly. I'd clarify this as "unexpected, unintended consequences". It's hard to know the impact of changing a global configuration variable in advance.

**Comment by szepeviktor** [comment] 2016-09-21 00:19
Since 2013 we have `$_SERVER['SERVER_NAME']` in CLI - providing one fills in `url` in the YAML file.
https://github.com/wp-cli/wp-cli/commit/8881f63add12d67fd7788bfbca9e87f094b05057

**Closed** 2016-10-03 22:34 UTC
Labels: bug, scope:framework
