### ISSUE TITLE
wp core install adds /wordpress to siteurl even when specified otherwise

### ISSUE THREAD

**Issue by yanickgirouard** [wp-cli/wp-cli#5335] opened 2020-01-13 13:35 UTC
* Using version 2.4.0 (latest version as of this ticket)

My web site's DocumentRoot points to `/www/wordpress`, and my site's URL should be `https://wordpress.localdomain/`. I use the following commands to install Wordpress from the `/www/wordpress` directory:

`wp core download --locale=fr_CA`

`wp core config --dbhost=localhost --dbname=wordpress --dbuser=wpuser --dbpass=wpuser`

`wp core install --url=https://wordpress.localdomain/ --title="Wordpress Local" --admin_name=wpadmin --admin_password=wpadmin --admin_email=myemail@localdomain.com`

When I try to access the site, the theme is broken (css not loading, missing images, etc...) and I see it's looking for https://wordpress.localdomain/wordpress/... instead of looking for files at the root.

If I undo the install and use the web installer instead, it's fine.

If I use the wp-cli method, and use the `wp option get siteurl` command, I see it has added /wordpress to the URL.

I can fix it by resetting the siteurl correctly using `wp option set siteurl https://wordpress.localdomain`, but why should I have to do this?

I saw a [previous ticket](https://github.com/wp-cli/wp-cli/issues/2563) dating from 2016 that was reporting the same thing but it had been fixed since. Would this be a regression?

Edit: The `home` option is also affected and has `/wordpress` added. Can also be fixed with the `wp option set` command.

**Comment by JamesTheHacker** [comment] 2020-01-26 23:57
Similar problem
    ./wp-cli.phar core install --url=http://cbdhut.home/
And then
    ./wp-cli.phar option get home
Returns
    http://cbdhut.homehome

**Comment by TomaszGasior** [comment] 2020-03-16 20:21
I have similar problem with 2.4.0. I have `testowy.xxxxx.pl` domain inside `/home/username/domains/testowy.axxxz.pl/public_html`. When I try to run `wp core install … --url=http://testowy.axxxz.pl` WordPress is installed with siteurl pointing to `http://testowy.axxxz.plaxxxz.pl/public_html`. :(

**Comment by Rahe** [comment] 2023-06-08 13:28
Hello,

On version 2.8.1 I have no issue at all for this case.
Everything runs fine and the domain url and scheme are respected.

Nicolas,

**Comment by swissspidy** [comment] 2023-11-10 20:27
@yanickgirouard @JamesTheHacker @TomaszGasior Given the latest command, is one of you able to reproduce this still?

**Comment by TomaszGasior** [comment] 2024-02-03 22:28
@swissspidy I am not able to reproduce [my problem](https://github.com/wp-cli/wp-cli/issues/5335#issuecomment-599740971) with latest release.

**Comment by swissspidy** [comment] 2024-02-04 17:11
Thanks! I'm closing this for now then.

**Closed by swissspidy** 2024-02-04 17:11 UTC
Labels: state:unconfirmed
