### ISSUE TITLE
Upgrade HTML output

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#1606] opened 2015-01-14 16:27 UTC
I've got output from `wp-admin/includes/class-wp-upgrader-skins.php` while updating from 3.9.2 to 4.1.

```html
<p>Néhány dolgot a fordításban frissíteni kell. Csak néhány másodpercet vesz igénybe.</p>
<div class="update-messages lp-show-latest"><h4>Fordítások frissítése WordPress (hu_HU)&#8230;</h4><p>A letöltés a <span class="code">https://downloads.wordpress.org/translation/core/4.1/hu_HU.zip</span>&#8230; helyről folyamatban van</p>
<p>Frissítés kicsomagolása...&#8230;</p>
<p>Legfrissebb verzió telepítése &#8230;</p>
<p>A fordítás frissítése megtörtént.</p>
</div><script type="text/javascript">
                                (function( wp ) {
                                        if ( wp && wp.updates.decrementCount ) {
                                                wp.updates.decrementCount( "translation" );
                                        }
                                })( window.wp );
                        </script></div></div>
```

In english: Some of your translations need updating. Sit tight for a few more seconds while we update them as well.

**Comment by danielbachhuber** [comment] 2015-01-14 17:11
Duplicate of #1501

**Closed by danielbachhuber** 2015-01-14 17:11 UTC
