### ISSUE TITLE
Not totally compatible with in busybox or alpine linux

### ISSUE THREAD

**Issue by jc21** [wp-cli/wp-cli#4246] opened 2017-07-26 01:23 UTC
Despite my linux environment meeting the requirements listed on the installation instructions, I've noticed wp-cli makes some assumptions with the linux environment that don't make it compatible with Alpine linux in particular, but may extend to other cut down versions of linux.

1. `wp-cli.phar --help` tries to use `less -r`, but in busybox version of less, -r is not an option and it immediately throws:

```
less: unrecognized option: r
BusyBox v1.26.2 (2017-06-11 06:38:32 GMT) multi-call binary.
...
```

Another command such as `wp-cli.phar plugin list` does work however.

2. The following error is echoed for all commands, which I assume is related to color output:

```
env: can't execute 'tput': No such file or directory
```

#2 is not a big deal for me and doesn't prevent functionality, however #1 does block some output of the command.

**Comment by gitlost** [comment] 2017-07-26 08:56
Hi @jc21, for the first issue you can set the environment variable `PAGER` to be what you want.

The second issue is caused by `Shell::columns()` in `php-cli-tools` https://github.com/wp-cli/php-cli-tools/blob/master/lib/cli/Shell.php#L53. The error should be suppressed. I'll open an issue on the `php-cli-tools` repo for it.

**Comment by danielbachhuber** [comment] 2017-07-26 11:49
Closing in favor of https://github.com/wp-cli/php-cli-tools/issues/112

**Closed by danielbachhuber** 2017-07-26 11:49 UTC

**Comment by emcniece** [comment] 2017-08-29 19:34
For those seeking a solution: `PAGER='busybox less'`

https://github.com/pry/pry/issues/1494#issuecomment-318067013

**Comment by nebulon42** [comment] 2017-08-30 19:53
@danielbachhuber Please reopen. The referenced issue does not solve the issue with `less`. I think this is a bug.

**Comment by danielbachhuber** [comment] 2017-08-30 19:56
@nebulon42 Can you create a new issue please, with details about the bug and steps to reproduce? Thanks.
