### ISSUE TITLE
Using Dotenv for DOMAIN_CURRENT_SITE makes all wp commands fail

### ISSUE THREAD

**Issue by lannor** [wp-cli/wp-cli#1766] opened 2015-04-17 12:14 UTC
Hey!

I'm trying to make my Wordpress setup easier by breaking out the environment-variables (database connection and domain etc) from wp-config.php to a .env file with the help of [https://github.com/vlucas/phpdotenv](https://github.com/vlucas/phpdotenv). 

Everything works except the define for DOMAIN_CURRENT_SITE. 

Code:

    <?php

    // Load composer and more..
    require_once(__DIR__ . '/my-custom-setup.php');

    // Show multisite settings in backend
    define('WP_ALLOW_MULTISITE', true);

    // ** MySQL settings ** //
    /** The name of the database for WordPress */
    define('DB_NAME', getenv('DB_NAME'));

    /** MySQL database username */
    define('DB_USER', getenv('DB_USER') ?: 'root');

    /** MySQL database password */
    define('DB_PASSWORD', getenv('DB_PASSWORD') ?: '');

    /** MySQL hostname */
    define('DB_HOST', getenv('DB_HOST') ?: 'localhost');

    /** Database Charset to use in creating database tables. */
    define('DB_CHARSET', getenv('DB_CHARSET') ?: 'utf8');

    /** The Database Collate type. Don't change this if in doubt. */
    define('DB_COLLATE', getenv('DB_COLLATE') ?: 'utf8_swedish_ci');

    define('AUTH_KEY',         'P(L%bV2Z@%l-2Jqk_Y^ZT#Gmv3ff.{uaRFxsx04,`|I?1?~%p~a3r`;A k<;PQ48');
    define('SECURE_AUTH_KEY',  'Bb>2#N${5GPb@Z6q|_H8)S;*g<KZgMtFDB~A,+II|c;p,c.pbF*uHN5^J?h:N{rE');
    define('LOGGED_IN_KEY',    'Vo~an>0@d1,RW1SD{q53B$O?x[*xhH(0-H+{N ~u?($1J.IW+&fxO5:OWn@t$=Tt');
    define('NONCE_KEY',        'iE9tZe1A?U[|r+f+4#CN|G8BmEH=Gscl^NZd8L+Vx{#A8@7|8:E|I(rmU;C[a*RT');
    define('AUTH_SALT',        'q]F_II}-zp)Z[k85*Wohvs_M a+i @`xzT:[^N-pL..`a2?F#qNy+,_&(LimeP<4');
    define('SECURE_AUTH_SALT', 's,c%:6&]1]p)wj/Ru8A(X{Bvfn0J<(a>=x<qi%X8@UU4.PYWXUR`B0mdqCkW03$i');
    define('LOGGED_IN_SALT',   'x9{cG2|h(z *5X:I.1np{^m>-+$O/d2Og#6S@c~aBE]Bk>$1qqZ1l<sn9(s!^uX-');
    define('NONCE_SALT',       'FQA#nWmDR?*U]{YY.iE~nL96`#na_(UB#jNZ1PHxy ?H)#Mc?|Nlq7p`y;+{Beae');

    $table_prefix = 'wp_';

    define('MULTISITE', true);
    define('SUBDOMAIN_INSTALL', false);
    $base = '/';
    define('DOMAIN_CURRENT_SITE', getenv('DOMAIN'));     <---- PROBLEM
    define('PATH_CURRENT_SITE', '/');
    define('SITE_ID_CURRENT_SITE', 1);
    define('BLOG_ID_CURRENT_SITE', 1);

    /* That's all, stop editing! Happy blogging. */

    /** Absolute path to the WordPress directory. */
    if ( !defined('ABSPATH') )
      define('ABSPATH', dirname(__FILE__) . '/');

    /** Sets up WordPress vars and included files. */
    require_once(ABSPATH . 'wp-settings.php');

When running `wp` commands I get this notice:

    Notice: Undefined index: REQUEST_URI

However, that is just because I use the `$_SERVER['REQUEST_URI']` at a place in my code. Otherwise it's (`wp_cli`) just totally quite. If I put a `var_dump(getenv('DOMAIN'));` before the `DOMAIN_CURRENT_SITE` - declaration it sure gets printed to the terminal. 

    user ~/path/to/my/code
    > wp site url 1
    string(11) "domain.dev"
    Notice: Undefined index: REQUEST_URI 

Before `wp_cli` arrived in my life I built my own ghetto task runner for Wordpress and I remember Wordpress shutting me down (quietly) if I didn't set the `REQUEST_URI` part of the `$_SERVER`-variable myself (`$_SERVER['REQUEST_URI'] = 'mydomain.dev';)`. This is probably what happens here too.

Howevery, `wp_cli` usually handles this but it doesn't work when the value for `DOMAIN_CURRENT_SITE` comes from the `getenv()` function (or any other function, tried with a `foo()` that returned `'mydomain.dev'`, but no dice).

If I hardcode the `DOMAIN_CURRENT_SITE` constant all works fine, but I don't want to have to do that, since I want it to be in a .env-file. 

Is there anything I can do here? 

Thanks!

**Comment by theMikeD** [comment] 2015-04-17 13:54
"However, that is just because I use the $_SERVER['REQUEST_URI'] at a place in my code."

This is the root issue. I brought it up in #1734 too. It's a known problem despite that issue being marked as "unconfirmed." I suggested using #785 to track this issue in one spot.

**Comment by danielbachhuber** [comment] 2015-04-17 14:00
I'm not sure why your domain is in `$_SERVER['REQUEST_URI']`, but you can't expect all `$_SERVER` variables to be properly populated in the CLI context. Your code will need to be more fault tolerant.

**Closed by danielbachhuber** 2015-04-17 14:00 UTC
