### ISSUE TITLE
core install creates wrong URL in wp_options

### ISSUE THREAD

**Issue by eduardoarandah** [wp-cli/wp-cli#1815] opened 2015-05-01 17:11 UTC
core install creates a wrong URL (check image)

In wp_options saves it as: http://hotelsanjosecoatepec.locloc 
instead of http://hotelsanjosecoatepec.loc

![xxx](https://cloud.githubusercontent.com/assets/4065733/7433859/2aa57f20-effb-11e4-9820-d9a4c5c92954.png)

My computer: 
windows 8 
wampserver 2.5

    php wp-cli.phar --path="C:\wamp\www\hotelsanjosecoatepec.loc" core download --locale=es_ES
    
    php wp-cli.phar --path="C:\wamp\www\hotelsanjosecoatepec.loc" core config --dbname=hotelsanjosecoatepec --dbuser=root
    
    php wp-cli.phar --path="C:\wamp\www\hotelsanjosecoatepec.loc" db create hotelsanjosecoatepec
    
    php wp-cli.phar  --path="C:\wamp\www\hotelsanjosecoatepec.loc" --title="Hotel San Jose Plaza Coatepec" --admin_user="admin" --admin_password="passwordhere" --admin_email="emailhere@gmail.com" --url="http://hotelsanjosecoatepec.loc" core install

**Comment by danielbachhuber** [comment] 2015-05-01 23:34
Dupe of #1814

**Closed by danielbachhuber** 2015-05-01 23:34 UTC
