### ISSUE TITLE
user create Invalid address: wordpress@

### ISSUE THREAD

**Issue by gbcxjoe** [wp-cli/wp-cli#3378] opened 2016-09-07 16:53 UTC
HI

Using:
WP-CLI version:	0.24.1
Ubuntu 14.04

when creating a new user with the following command, we get the error below.
/wp user create GBewuser joe@joe.com --send-email --role=administrator --allow-root

PHP Fatal error:  Uncaught exception 'phpmailerException' with message 'Invalid address: wordpress@' in /home/scripttestdev/public_html/wp-includes/class-phpmailer.php:946
Stack trace:
#0 /home/scripttestdev/public_html/wp-includes/pluggable.php(352): PHPMailer->setFrom('wordpress@', 'WordPress', false)
#1 /home/scripttestdev/public_html/wp-includes/pluggable.php(1726): wp_mail('joe@applelinks....', '[dev scripttest...', 'New user regist...')
#2 phar:///wp/php/commands/user.php(898): wp_new_user_notification(2, NULL, 'both')
#3 phar:///wp/php/commands/user.php(362): User_Command::wp_new_user_notification(2, 'p(@aK@8vGZc1')
#4 [internal function]: User_Command->create(Array, Array)
#5 phar:///wp/php/WP_CLI/Dispatcher/CommandFactory.php(67): call_user_func(Array, Array, Array)
#6 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#7 phar:///wp/php/WP_CLI/Dispatcher/Subcommand.php(372): call_user_func(Object(Closure), Array, Array)
#8 phar:///wp/php/WP_CLI/Runner.php(312): WP_CLI\Disp in /home/scripttestdev/public_html/wp-includes/class-phpmailer.php on line 946
Fatal error: Uncaught exception 'phpmailerException' with message 'Invalid address: wordpress@' in /home/scripttestdev/public_html/wp-includes/class-phpmailer.php:946
Stack trace:
#0 /home/scripttestdev/public_html/wp-includes/pluggable.php(352): PHPMailer->setFrom('wordpress@', 'WordPress', false)
#1 /home/scripttestdev/public_html/wp-includes/pluggable.php(1726): wp_mail('joe@app....', '[dev scripttest...', 'New user regist...')
#2 phar:///wp/php/commands/user.php(898): wp_new_user_notification(2, NULL, 'both')
#3 phar:///wp/php/commands/user.php(362): User_Command::wp_new_user_notification(2, 'p(@aK@8vGZc1')
#4 [internal function]: User_Command->create(Array, Array)
#5 phar:///wp/php/WP_CLI/Dispatcher/CommandFactory.php(67): call_user_func(Array, Array, Array)
#6 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#7 phar:///wp/php/WP_CLI/Dispatcher/Subcommand.php(372): call_user_func(Object(Closure), Array, Array)
#8 phar:///wp/php/WP_CLI/Runner.php(312): WP_CLI\Disp in /home/scripttestdev/public_html/wp-includes/class-phpmailer.php on line 946
PHP Fatal error:  Uncaught exception 'phpmailerException' with message 'Invalid address: wordpress@' in /home/scripttestdev/public_html/wp-includes/class-phpmailer.php:946

**Comment by danielbachhuber** [comment] 2016-09-07 16:56
Duplicate of #3374

This is an issue with WordPress core, and is fixed in 4.6.1

**Closed by danielbachhuber** 2016-09-07 16:56 UTC

**Comment by gbcxjoe** [comment] 2016-09-07 21:10
Still getting the error in 4.6.1

**Comment by danielbachhuber** [comment] 2016-09-07 21:21
> Still getting the error in 4.6.1

Ok. This is an issue with WordPress core, not WP-CLI.

**Comment by Ipstenu** [comment] 2016-09-19 18:10
FYI this is the bug - https://core.trac.wordpress.org/ticket/37736

**Comment by matmar-91** [comment] 2016-09-28 20:38
@gbcxjoe 
Simple workaround for this is creating php file where you set SERVER_NAME variable, which is not available from CLI, but used by wordpress core. Then you can pass this file to command with --require flag. 

your_file.php
`<?php 
$_SERVER[ 'SERVER_NAME' ] = 'your.host.com'`

Now you can for example do this:
` wp user create username email@example.com --display_name="John Doe" --first_name=John --last_name=Doe --send-email --require=your_file.php`

**Comment by shynii** [comment] 2016-12-11 08:59
wp-includes/pluggable.php:352

Replace
`$phpmailer->setFrom( $from_email, $from_name, false );`

By
`$phpmailer->setFrom( "wordpress@foobar.com", $from_name, false );`

**Comment by Ipstenu** [comment] 2016-12-11 18:13
@shynii - The point is that WordPress itself isn't passing the domain to the $from_email variable.

**Comment by kikoseijo** [comment] 2016-12-13 09:56
Same here on 4.7, seems to be problem with the CORE of WORDPRESS.-

**Comment by Ipstenu** [comment] 2016-12-13 15:45
Hey guys? Stop beating a dead horse.

Read https://core.trac.wordpress.org/ticket/37736 - It's an issue in core. And Daniel instituted a fix in https://github.com/wp-cli/wp-cli/pull/3449

Upgrade WP-CLI and stop posting here (Daniel, you may ask well lock this ticket since people aren't RTFMing)

**Comment by danielbachhuber** [comment] 2016-12-13 17:00
Thanks @Ipstenu
