### ISSUE TITLE
Error establishing a database connection when DB_HOST contains "p:" for persistent database connections

### ISSUE THREAD

**Issue by jbwtech** [wp-cli/wp-cli#5109] opened 2019-03-22 15:26 UTC
Our Wordpress installation recently switched to using persistent connections to the remote MySQL database server.  However, today when attempting to search the database with 'wp db search', wp-cli fails to parse the DB_HOST string in wp-config.php with 'p:' before the database server hostname.

**Comment by schlessera** [comment] 2019-03-23 10:37
Okay, the problem is probably coming from the `mysql_host_to_cli_args()` method:

https://github.com/wp-cli/wp-cli/blob/master/php/utils.php#L419-L441

Would you be interested in providing a PR for adding support for the `p:` modifier?

**Comment by jbwtech** [comment] 2019-03-23 17:35
I have not looked at the source code yet but I can now that I now where to look. I can think of two theoretical approaches. The first would be to just ignore the “p:” and make a regular connection, by changing the way the host string is parsed. That shouldn’t be too intrusive or difficult to implement. Also, a persistent connection doesn’t really add any benefit to wp-cli, since it’s only used once for the duration of the command. At least I assume it does. 

--Brent

(Mobile)

**Comment by schlessera** [comment] 2019-03-23 19:50
@jbwtech Yes, I think ignoring the `p:` is the way to go. Also keep in mind that WP-CLI will use the PHP cli SAPI, not the PHP-FPM one.

**Comment by danielbachhuber** [comment] 2019-03-25 16:34
Fixed in #5115

**Closed by danielbachhuber** 2019-03-25 16:34 UTC
Labels: bug
