### ISSUE TITLE
Deprecated notices on PHP 8.1.1

### ISSUE THREAD

**Issue by michacassola** [wp-cli/wp-cli#5623] opened 2022-02-15 18:06 UTC
Hey, installing wp-cli I get the following deprecated messages:

```
Deprecated: rtrim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/utils.php on line 981

Deprecated: realpath(): Passing null to parameter #1 ($path) of type string is deprecated in phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php on line 301

Deprecated: Return type of Requests_Cookie_Jar::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/wp-cli/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 63

Deprecated: Return type of Requests_Cookie_Jar::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/wp-cli/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 73

Deprecated: Return type of Requests_Cookie_Jar::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/wp-cli/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 89

Deprecated: Return type of Requests_Cookie_Jar::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/wp-cli/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 102

Deprecated: Return type of Requests_Cookie_Jar::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/wp-cli/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 111

Deprecated: Return type of Requests_Utility_CaseInsensitiveDictionary::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/wp-cli/vendor/rmccue/requests/library/Requests/Utility/CaseInsensitiveDictionary.php on line 40

Deprecated: Return type of Requests_Utility_CaseInsensitiveDictionary::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/wp-cli/vendor/rmccue/requests/library/Requests/Utility/CaseInsensitiveDictionary.php on line 51

Deprecated: Return type of Requests_Utility_CaseInsensitiveDictionary::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/wp-cli/vendor/rmccue/requests/library/Requests/Utility/CaseInsensitiveDictionary.php on line 68

Deprecated: Return type of Requests_Utility_CaseInsensitiveDictionary::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/wp-cli/vendor/rmccue/requests/library/Requests/Utility/CaseInsensitiveDictionary.php on line 82

Deprecated: Return type of Requests_Utility_CaseInsensitiveDictionary::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/wp-cli/vendor/rmccue/requests/library/Requests/Utility/CaseInsensitiveDictionary.php on line 91
```

**Comment by lstellway** [comment] 2022-02-16 20:28
Seeing the same deprecation notices on PHP `8.1.2`. 

Looks like it's complaining purely about the [rmccue/requests](https://packagist.org/packages/rmccue/requests) package. The current dependency requires version `^1.8` ([reference](https://github.com/wp-cli/wp-cli/blob/f94e77d4563c66c04b582eb9fa8b4652b11ed0c2/composer.json#L14)). 

The package is now at `2.0.1`. I wonder if this could be updated without issue?

**Comment by schlessera** [comment] 2022-02-16 23:37
Yes, the Requests package needs updating for these deprecation notices to go away. We've been discussing how best to do that without it causing issues with WordPress.

The main problem is that WP-CLI needs to work with both old and new versions of WordPress, and WordPress 6.0 will most likely upgrade Requests to v2+ as well.

**Comment by swissspidy** [comment] 2022-07-18 13:02
The first two ones notices are not related to Requests. Addressing them in #5658

**Comment by RoundAboutWEB** [comment] 2022-09-15 07:47
same with PHP 8.1.10
When do you think the problem will be fixed?

**Comment by chief1983** [comment] 2022-11-09 22:25
Just tested updating our env to PHP 8.1.12.  Saw that even with the latest wp-cli, it still depends on requests 1.8.x, which is still triggering these notices.  I don't see any indication that WP 6.0 or even 6.1 has bumped that up either, as wp-cli itself is the source of the dependency from what I can tell, and is still behind the latest v2 release.  I'm not entirely sure these notices are fixed in the latest requests, but we'll be moving to PHP 8.0.25 this upgrade round instead of 8.1.  Just wondering if there is still any plan to work to get these notices addressed somehow?  PHP 8.2 is almost out now :)

**Comment by rpodric** [comment] 2022-11-26 05:20
Glad to have found this thread.

Does it affect functionality in some subtle way or is it just a warning?

**Comment by markjaquith** [comment] 2022-12-05 22:46
@rpodric It throws `Deprecated` notices. Doesn't seem to prevent it from working, but I consider my error logs getting absolutely flooded to be a problem worth solving.

@schlessera could WP-CLI use a patched version of Requests that adds `#[\ReturnTypeWillChange]` as a temporary workaround? I just patched WordPress core to be 8.1-compatible, but then realized that I'd have to do the same to WP-CLI (and some versions of it are on systems where I can't patch it).

**Comment by schlessera** [comment] 2022-12-06 07:49
The problem with patching is that the usual ways to do that via Composer will not work if you pull in WP-CLI into your own project via Composer (as the patching scripts will only run for the root project).
What I could look at is pulling in a separate branch of Requests with these attributes already set...

**Comment by ecotechie** [comment] 2022-12-30 04:37
Dare I say to use an alias for the time being?
alias wp="wp $@ 2> /dev/null

**Comment by techieshark** [comment] 2023-01-02 11:48
And PHP 7.4 is no longer supported - https://www.php.net/supported-versions.php

**Comment by danielbachhuber** [comment] 2023-01-03 00:45
> And PHP 7.4 is no longer supported

It's not _officially_ supported. However, some hosts are maintaining forks for the foreseeable future.

**Comment by s-a-s-k-i-a** [comment] 2023-01-30 16:55
For the time being, I am using an mu plugin with following filters to prevent these deprecation notices from spamming my debug log:

`add_filter( 'deprecated_constructor_trigger_error', '__return_false' );
add_filter( 'deprecated_function_trigger_error', '__return_false' );
add_filter( 'deprecated_file_trigger_error', '__return_false' );
add_filter( 'deprecated_argument_trigger_error', '__return_false' );
add_filter( 'deprecated_hook_trigger_error', '__return_false' );`

Maybe this is of help to others as well.
Let's just hope someone finds the time to address this in core.

**Comment by rpodric** [comment] 2023-02-13 22:53
I implemented that mu-plugin yesterday but today see the usual bounty of Requests_Cookie_Jar and Requests_Utility_CaseInsensitiveDictionary entries produced. 

I'm trying to decipher the above five lines to see what each should specifically filter. Do you have a reference for that? I don't think you can tell by name alone (trigger, argument, file etc).

**Comment by maksam07** [comment] 2023-02-17 11:10
> I implemented that mu-plugin yesterday but today see the usual bounty of Requests_Cookie_Jar and Requests_Utility_CaseInsensitiveDictionary entries produced.
> 
> I'm trying to decipher the above five lines to see what each should specifically filter. Do you have a reference for that? I don't think you can tell by name alone (trigger, argument, file etc).

https://developer.wordpress.org/reference/hooks/deprecated_constructor_trigger_error/

**Comment by petertwise** [comment] 2023-02-22 01:25
Obviously PHP 8.1+ compatibility is the goal, but for now - bare minimum - I want to hide depreciated notices that originate from WP CLI, but _not_ hide depreciated notices that originate from themes/plugins/core. Is that possible? Does not currently seem possible to silence these without turning off WP_DEBUG.

**Comment by jimmyadaro** [comment] 2023-02-26 07:48
Neither `WP_DEBUG` set to false, nor set multiple `add_filter`, nor `error_reporting()` fixed this issue for me, so I just did what maybe the Core should do: add `#[\ReturnTypeWillChange]` before each problematic method, like so:

```php
// File: wp-includes/Requests/Cookie/Jar.php

#[\ReturnTypeWillChange]
public function offsetExists($key) {
    $key = strtolower($key);
    return isset($this->data[$key]);
}

// ...

#[\ReturnTypeWillChange]
public function offsetGet($key) {
    $key = strtolower($key);
    if (!isset($this->data[$key])) {
        return null;
    }

    return $this->data[$key];
}

// ...
```

And so on for the entire file. Same thing for the issues in `CaseInsensitiveDictionary`. 
That removed all the warnings for me (currently using PHP 8.1.16).

**Comment by petertwise** [comment] 2023-03-02 20:37
I don't want to mess with core files, so for now I'm doing a pretty wacky thing:

edit your ~/.bashrc file and add:

```
wp2 ()
{
  wp config set WP_DEBUG false --raw && wp $@ && wp config set WP_DEBUG true --raw
}
```
Now I can use `wp2` in place of `wp` with WP_DEBUG off, while still leaving it on when I'm done with the cli command.

**Comment by ehausen** [comment] 2023-03-14 16:00
So what would be the best way to suppress Deprecated messages from WP CLI command line output?

Suggested in this thread

- `alias wp="wp $@ 2> /dev/null`
- `wp2 ()
{
  wp config set WP_DEBUG false --raw && wp $@ && wp config set WP_DEBUG true --raw
}`


Any unwanted side effects?

**Comment by ehausen** [comment] 2023-03-15 12:16
`alias wp="wp $@ 2> /dev/null` Did not work for me. 

I ended up silencing PHP Deprecated messages by making an alias by putting
`alias wp="php -d error_reporting=24575 /usr/local/bin/wp"` in my .bash_profile file
Of course you could also set the error reporting in php.ini, but then it would affect all php.

**Comment by danielbachhuber** [comment] 2023-03-15 12:27
FYI - we're planning to have this fixed in the next release, whenever that may be.

**Comment by cmaskaler** [comment] 2023-03-15 23:13
Fix it please.

**Comment by pf1gura** [comment] 2023-03-15 23:30
Based on the TRAC issue provided in one of previous messages issue was fixed in WordPress and will be released as part of WordPress 6.2

https://core.trac.wordpress.org/ticket/54504

**Comment by petertwise** [comment] 2023-03-15 23:37
Try out `wp core update --version=6.2-RC1` - working for me!

**Comment by RichardTMiles** [comment] 2023-04-07 10:46
https://github.com/orgs/wp-cli/discussions/5765

**Closed** 2023-05-02 08:58 UTC
Labels: scope:framework, upstream-bug, bug

**Comment by Flimm** [comment] 2023-05-09 11:42
To be clear, the fix for this has been merged, but has not yet been released. So the latest release of wp CLI still has this issue.

**Comment by c0ntax** [comment] 2023-06-01 06:57
Hi there. Just thought I'd pop by and let you know that the upgrade to using v2.x of rmccue/requests seems to break [ElasticPress](https://github.com/10up/ElasticPress)'s autosuggest feature and just broke my site in dev. I'm mainly leaving this note here just in case anyone else is on the same journey as I am, trying to track down what happened. 😉

**Comment by danielbachhuber** [comment] 2023-06-01 10:59
@c0ntax (and anyone else who runs into this): Please open a new issue with reproduction steps if you can!
