### ISSUE TITLE
Why relying on the MySQL commands only ? Is a fallback to PHP extension possible ?

### ISSUE THREAD

**Issue by shulard** [wp-cli/wp-cli#3819] opened 2017-02-18 09:13 UTC
Hello,

I'm currently trying to build a CI pipeline to deploy my WordPress website automatically from a Git repository. I've chose to use wp-cli to perform common WordPress tasks (plugin installation, core installation / update) but I face a problem...

My CI pipeline rely on docker :

* A build container which will contains my code and on which I'll ran some tests / builds
* A mysql image started as a service (mysql cli tools are not accessible by my build container)

MySQL is accessible from my build container but only through the network. I found that wp-cli rely only on MySQL cli commands to perform database related tasks in the [`php/utils.php`](https://github.com/wp-cli/wp-cli/blob/master/php/utils.php) file at line 419 : `run_mysql_command`

Maybe I miss something but MySQL commands are not always available on the WordPress installed server.

Do you think it's a good idea to update that code to :

* Rely on MySQL commands when available
* Fallback on `pdo_mysql` or php mysql extension

If so, I can work on a PR 😄...

**Comment by szepeviktor** [comment] 2017-02-20 12:11
> Fallback on pdo_mysql or php mysql extension

Core uses ancient mysql and mysqli. PDO is missing from the core.

**Comment by szepeviktor** [comment] 2017-02-20 12:12
How you substitute `mysqldump`?

**Comment by szepeviktor** [comment] 2017-02-20 12:13
Which mysql package excludes MySQL cli commands?

**Comment by shulard** [comment] 2017-02-20 13:12
I know that PDO is missing from the core, maybe relying on mysql native php extension can be enough.

I don't know how I can substitute MySQL dump. For me the problem is that WP-CLI doesn't handle the case when MySQL binaries are not installed on the machine :

```
sh: mysql: not found
```

For example if I have a MySQL server detached from my Application server, the last one don't need any MySQL CLI command. I know that there are some package (mysql-client, mariadb-client) that allow to install only the client binaries but they are not required on the machine...

I think that most of the time, WP-CLI don't need to rely on an external MySQL command because PHP is bundled with a mysql client. It also must fail with an clear error message when the binaries are not available.
For example with `mysqldump`, the database export command just can't be used if the binary missing.

**Comment by danielbachhuber** [comment] 2017-02-20 15:21
Duplicate of https://github.com/wp-cli/wp-cli/issues/1324#issuecomment-241722285

**Closed by danielbachhuber** 2017-02-20 15:21 UTC

**Comment by gitowiec** [comment] 2017-08-26 23:34
It could be superb to allow wp-cli run on pure wordpress docker container (in that case there is no mysql client).

**Comment by schlessera** [comment] 2017-08-27 06:36
Related: https://github.com/wp-cli/ideas/issues/52

**Comment by gitlost** [comment] 2017-08-27 12:43
@gitowiec which `wp` commands are failing for you? From what I can see on a quick scan of the source, the only commands that directly use the `mysql` client executable are `wp config create` (which can be got around by using `--skip-check`) and `wp db` commands.

**Comment by gitowiec** [comment] 2017-09-01 21:45
@gitlost thanks, I managed to run `wp db` on my container. I installed mysql-client and connected it with db container.
