### ISSUE TITLE
Please use tar.gz over zip archives

### ISSUE THREAD

**Issue by bitstarr** [wp-cli/wp-cli#2990] opened 2016-06-08 12:40 UTC
I noticed wp-cli is always downloading the zip archive for the core. Extracting the zip is very slow on my Linux machine while tar.gz extraction is much faster.

Please add a parameter or set this behaviour as default.

Thanks

**Comment by szepeviktor** [comment] 2016-06-09 23:16
How would you untar a tar archive in PHP?

**Comment by bitstarr** [comment] 2016-06-11 09:38
looks good. i will update and try next week

**Comment by danielbachhuber** [comment] 2016-06-11 23:24
> Extracting the zip is very slow on my Linux machine while tar.gz extraction is much faster.

Can you diagnose this issue at greater depth, and produce a hypothesis to the cause?

Some initial thoughts:

* I'm 👎 on adding an option to switch archive types.
* I'm not sure whether WordPress.org supports `.tar.gz` for all archive types.
* I'm not certain that extracting `.tar.gz` is generally faster than extracting `.zip` on all platforms, which means changing the archive format could have a negative impact on other users.

Generally, it seems like you should solve this problem with your machine, not by changing WP-CLI's behavior.

**Comment by bitstarr** [comment] 2016-06-13 08:15
In my experience WordPress is serving the core as tar.gz but not the plugins.
My preferred way is to set an option on core download.

And yes, you are right, maybe it's only my machine. But i am expecting this on all my virtual servers as well. Is unzipping slower on virtualized environments?

**Comment by danielbachhuber** [comment] 2016-06-13 12:05
> But i am expecting this on all my virtual servers as well. Is unzipping slower on virtualized environments?

I don't believe so, no. Performance considerations of `.zip` vs. `.tar.gz` hasn't ever come up before as a support issue, so I feel reasonably confident this is an issue with your server configuration and not something that needs to be fixed with WP-CLI.

**Closed by danielbachhuber** 2016-06-13 12:05 UTC
Labels: state:unconfirmed
