### ISSUE TITLE
"Not enough memory" error on Windows and PHP 7.1+

### ISSUE THREAD

**Issue by Rarst** [wp-cli/wp-cli#4593] opened 2017-12-27 15:40 UTC
I am getting `Not enough memory.` error immediately on WP CLI launch, outside of WP context altogether.

I seem to get it consistently on PHP 7.1 in my dev stack and clean vanilla download of PHP 7.2

```
C:\server>php --version && php ext/wp-cli.phar

PHP 7.1.1 (cli) (built: Jan 18 2017 18:51:14) ( ZTS MSVC14 (Visual C++ 2015) x86 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

Not enough memory.
```

```
C:\server>"php72/php" --version && "php72/php" ext/wp-cli.phar

PHP 7.2.0 (cli) (built: Nov 29 2017 00:17:00) ( ZTS MSVC15 (Visual C++ 2017) x86 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies

Not enough memory.
```

No error on clean vanilla download of PHP 7.0

```
C:\server>"php70/php" --version && "php70/php" ext/wp-cli.phar

PHP 7.0.26 (cli) (built: Nov 22 2017 13:18:45) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

NAME

  wp

DESCRIPTION

  Manage WordPress through the command-line.
...
```

Unaffected by `memory_limit` configuration.

**Comment by Rarst** [comment] 2017-12-28 15:47
I seem to have narrowed this down to a `pass_through_pager()` in the Help command, specifically last return line: https://github.com/wp-cli/wp-cli/blob/master/php/commands/help.php#L132

Not too familiar with `proc_*` functions to further tell what exactly goes wrong there.

**Comment by schlessera** [comment] 2017-12-28 17:27
I have a hunch:

I suspect that the following `while` loop runs endlessly, because the modification to `$cmd` does not work as expected: https://github.com/wp-cli/wp-cli/blob/master/php/utils.php#L1348

**Comment by gitlost** [comment] 2017-12-28 19:29
I can't reproduce this on Windows 10 with (downloaded from http://windows.php.net/download):
```
PHP 7.1.12 (cli) (built: Nov 23 2017 04:34:08) ( ZTS MSVC14 (Visual C++ 2015) x86 )
```
or
```
PHP 7.2.0 (cli) (built: Nov 29 2017 00:17:00) ( ZTS MSVC15 (Visual C++ 2017) x86 )
```
or with their x64/NTS versions (or with PHP 7.0) evoking either the nightly or stable wp-cli.

> I suspect that the following while loop runs endlessly

I doubt it....:)

**Comment by Rarst** [comment] 2017-12-29 06:51
I am on Windows 7, we had someone else in slack unable to reproduce on 10 as well. Unfortunately I don't have 10 on hand right now myself.

**Comment by schlessera** [comment] 2017-12-29 08:29
Oh, I didn't notice that the `proc_open_compat()` code is so fresh. Maybe it _fixes_  the actual problem...
@rarst Could you try running the WP-CLI nightly? Depending on how you installed it, a simple `wp cli update --nightly` would do the trick.

**Comment by Rarst** [comment] 2017-12-29 08:52
I am running `master` checkout right now, is that the same?

**Comment by schlessera** [comment] 2017-12-29 08:52
Yes, should be the same.

**Comment by gitlost** [comment] 2017-12-29 10:03
Okay have reproduced with PHP 7.2.0 on a Windows 7 virtualbox - will report back when I set up cygwin/git/composer etc...!

**Comment by gitlost** [comment] 2017-12-29 13:44
Okay the "Not enough memory." error is actually being printed by the Windows 7 `more.com` program. It does this when wp-cli is run from `cmd.exe`, but not when run from the Cygwin Terminal.

The issue appears to be related to the console code page, as there's extra processing for this in PHP 7.1+ that wasn't in PHP 7.0, and apparently `more.com` doesn't support Unicode (65001). Setting the code page on the command line with `chcp 1252` fixes it on `cmd.exe`, as does adding these lines to `Help_Command::pass_through_pager()` in "php/commands/help.php" after setting the `$pager` variable:
```
if ( Utils\is_windows() && 'more' === $pager && version_compare( PHP_VERSION, '7.1', '>=' ) ) {
	sapi_windows_cp_set( 1252 );
}
```
So this might be worth doing, though it'd be better if it also determined that it was on Windows 7 and only do it then...

Another way around it if you have cygwin installed is to set the `PAGER` environment variable eg
```
SET PAGER=C:\cygwin64\bin\less
```
Or just run under the Cygwin Terminal (didn't try Git Bash).

**Comment by Rarst** [comment] 2017-12-30 15:01
Thank you! I've suspected it's somewhere in the binaries rather than PHP source, but didn't dug in far enough.

Set pager to `less` for myself locally for now.

**Comment by schlessera** [comment] 2018-01-02 12:30
Great debugging, @gitlost !

Do you think it makes sense to add a fix for this in WP-CLI, as you suggested?

**Comment by gitlost** [comment] 2018-01-02 13:15
Shucks thanks!

> Do you think it makes sense to add a fix for this in WP-CLI, as you suggested?

I think so, as being able to display help is so important. Also found out there's a `PHP_WINDOWS_VERSION_MAJOR` constant available so can make it specific to < Windows 10.

(I've actually done a fair bit to get the phpunit tests and (most of) the behat tests working on Windows 10 and on appveyor (Windows Server 2012 R2) so will be doing some PRs related to that soon... concentrating on getting https://github.com/wp-cli/embed-command/issues/18 in at the moment with a review/PR incoming very soon...)

**Closed** 2018-01-05 14:56 UTC
Labels: bug, command:help
