### ISSUE TITLE
wp connects to the wrong port

### ISSUE THREAD

**Issue by nevis2us** [wp-cli/wp-cli#5505] opened 2021-03-18 10:38 UTC
Some wp subcommands do not use the port explicitly specified in DB_HOST.

I have a mariadb server running on a non-standard port. It can be reached either through a port or a socket:

define( 'DB_HOST', 'localhost:3307' );
define( 'DB_HOST', 'localhost:/var/opt/rh/rh-mariadb102/lib/mysql/mysql.sock' );

'wp db cli' works in both cases. 'wp plugin list' and 'wp site list' only work with the socket. Using these subcommands with the port leads to connection errors. I didn't check other subcommands.

Changing mysqli.default_port in php.ini doesn't help. This gives an impression 3306 is hardcoded.

$ wp cli info
OS:	Linux 2.6.32-754.35.1.el6.x86_64 #1 SMP Sat Nov 7 12:42:14 UTC 2020 x86_64
Shell:	/bin/bash
PHP binary:	/opt/rh/rh-php70/root/usr/bin/php
PHP version:	7.0.27
php.ini used:	/etc/opt/rh/rh-php70/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/var/www/vhosts/wordpress-test
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.4.0

**Comment by schlessera** [comment] 2021-05-11 15:12
For `wp db cli`, WP-CLI is responsible for configuring the database access.

For `wp plugin list` and `wp site list` however, WP-CLI only uses the function that the WordPress installation provides, therefore this seems to be a misconfiguration in the `wp-config.php` file or some other problem with the WordPress installation.

Closing as this is most probably not caused by WP-CLI.

**Closed by schlessera** 2021-05-11 15:12 UTC

**Comment by nevis2us** [comment] 2021-06-23 21:32
https://core.trac.wordpress.org/ticket/33842

> Whenever you specify "localhost" or "localhost:port" as server, the MySQL client library will override this and try to connect to a local socket (named pipe on Windows). If you want to use TCP/IP, use "127.0.0.1" instead of "localhost". If the MySQL client library tries to connect to the wrong local socket, you should set the correct path as in your PHP configuration and leave the server field blank.
