### ISSUE TITLE
PHP notice when installing theme or plugin

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/wp-cli#2728] opened 2016-05-10 06:58 UTC
I am using `0.23.0`. I am getting notice when installing theme or plugin.
`
PHP Notice:  Undefined offset: 4 in phar:///usr/local/bin/wp/php/WP_CLI/DocParser.php on line 124
Notice: Undefined offset: 4 in phar:///usr/local/bin/wp/php/WP_CLI/DocParser.php on line 124
`
No package installed. WP version 4.5.2.
I see this error when `wp theme install simple-life`. Notice displays but theme is installed anyway.

**Comment by danielbachhuber** [comment] 2016-05-10 11:43
Duplicate of #2627

**Closed by danielbachhuber** 2016-05-10 11:43 UTC
